### ISSUE TITLE
zentasol 

### ISSUE THREAD

**Issue by trebor1974** [martinvw/vbusdecode#5]
Hallo Martin,

Ik heb een vraag voor je, en hoop dat je me kan helpen. Ik kwam je blog tegen op een website over home automation en een zentasol buffervat icm openhab via een usb-485 verloop (heb ik net besteld)

Wij zijn ons hele huis aan het verbouwen en alles word geautomatiseerd via openhab nou heb ik zelf  niet echt ervaring met openhab maar me zelf alles aangeleerd met vallen en opstaan. ze draait nu al een tijdje met een lading hue lampen en een lading arduino sensoren die ik heb gemaakt in 2 patch kasten en 500 meter cat6 kabel :D

Ik heb net een zentasol buffervat op de kop getikt die ik ook graag wil koppelen aan openhab en volgens mij heb jij het wiel al uit gevonden in deze, zou je mij kunnen vertellen hoe je dit precies heb gekoppelt ?

sorry als ik hier verkeerd ben en alvast bedenkt voor je tijd.

Met vriendelijk groet,

Robert

**Comment by martinvw** [comment]
Hello Robert,

I can and will tell you how I did it, I started a wiki https://github.com/martinvw/vbusdecode/wiki/Linking-my-Remeha---Zentasol-to-openHAB to give some explanation and code examples. The short story is that I wrote a python script which is ran by a cronjob and sends all Zentasol data over MQTT to a central server. openHAB picks up this MQTT-topics. I hope to complete the wiki in the upcomming weeks.

**Comment by trebor1974** [comment]
Thank you ! , i look forward to reading the rest of your wiki topic. i'm glad i dont have to do a invention of  that wheel again. so manny projects and only so much time.

Regards

Robert

**Comment by martinvw** [comment]
I think it should be complete now, questions please let me know.
